spring.application.name=fedu

server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/fedu_db
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.from=hieudtfptu@gmail.com
spring.mail.username=hieudtfptu@gmail.com
spring.mail.password=vpwohxfxufhjdfif
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
