server:
  port: 8080

spring:
  application:
    name: fedu

  datasource:
    url: jdbc:postgresql://ep-square-rain-aonmzhf3-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&prepareThreshold=0
    username: neondb_owner
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hieudtfptu@gmail.com
    password: ${MAIL_PASSWORD:}
    from: hieudtfptu@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: fedu
    serverUrl: http://localhost:${server.port}
    serverName: FEdu System
    title: FEdu System
    version: 1.0.0

jwt:
  expiryMinute: 15
  expiryHour: 1
  expiryDay: 30
  accessKey: ${JWT_ACCESS_KEY}
  refreshKey: ${JWT_REFRESH_KEY}
  resetKey: ${JWT_RESET_KEY}

app:
  frontend-url: http://localhost:5173
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000,http://localhost:5174,http://localhost:5175
